# Generated by Django 4.1.2 on 2023-03-21 10:53

import core.models
from django.db import migrations, models
import django_cpf_cnpj.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DadosMedicao',
            fields=[
                ('id_lente', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('OS', models.CharField(blank=True, max_length=255, null=True)),
                ('horizontal', models.FloatField(blank=True, null=True)),
                ('vertical', models.FloatField(blank=True, null=True)),
                ('diagonal_maior', models.FloatField(blank=True, null=True)),
                ('DNP', models.IntegerField(blank=True, null=True)),
                ('altura', models.IntegerField(blank=True, null=True)),
                ('leitura_direito', models.BooleanField(blank=True, null=True)),
                ('leitura_esquerdo', models.BooleanField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=core.models.upload_image_lente)),
                ('cnpjOtica', django_cpf_cnpj.fields.CNPJField(max_length=18)),
                ('cnpjLaboratorio', django_cpf_cnpj.fields.CNPJField(max_length=18)),
            ],
        ),
    ]
