# Generated by Django 4.1.2 on 2023-03-21 11:41

import cloudinary.models
import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_dadosmedicao_timestamp_alter_dadosmedicao_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dadosmedicao',
            name='timestamp',
        ),
        migrations.AlterField(
            model_name='dadosmedicao',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name=models.ImageField(blank=True, null=True, upload_to=core.models.upload_image_lente)),
        ),
    ]
