# Generated by Django 4.1.2 on 2023-03-21 11:45

import cloudinary.models
import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_dadosmedicao_timestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dadosmedicao',
            name='image_cloud',
            field=cloudinary.models.CloudinaryField(default=1, max_length=255, verbose_name='image'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dadosmedicao',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.upload_image_lente),
        ),
    ]
