# Generated by Django 4.1.2 on 2023-03-21 11:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_dadosmedicao_image_cloud_alter_dadosmedicao_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='dadosmedicao',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
