# Generated by Django 4.1.7 on 2023-03-24 13:22

import cloudinary.models
from django.db import migrations, models
import django.utils.timezone
import django_cpf_cnpj.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_dadosmedicao_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadosmedicao',
            name='cnpjLaboratorio',
            field=django_cpf_cnpj.fields.CNPJField(blank=True, max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='dadosmedicao',
            name='cnpjOtica',
            field=django_cpf_cnpj.fields.CNPJField(blank=True, max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='dadosmedicao',
            name='image_cloud',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='dadosmedicao',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
