# Generated by Django 4.1.7 on 2023-03-24 22:24

import uuid

import cloudinary.models
import django.utils.timezone
import django_cpf_cnpj.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DadosMedicao',
            fields=[
                ('id_lente', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('OS', models.CharField(blank=True, max_length=255, null=True)),
                ('horizontal', models.FloatField(blank=True, null=True)),
                ('vertical', models.FloatField(blank=True, null=True)),
                ('diagonal_maior', models.FloatField(blank=True, null=True)),
                ('DNP', models.IntegerField(blank=True, null=True)),
                ('altura', models.IntegerField(blank=True, null=True)),
                ('leitura_direito', models.BooleanField(blank=True, null=True)),
                ('leitura_esquerdo', models.BooleanField(blank=True, null=True)),
                ('image',
                 cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('timestamp', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('cnpjOtica', django_cpf_cnpj.fields.CNPJField(blank=True, max_length=18, null=True)),
                ('cnpjLaboratorio', django_cpf_cnpj.fields.CNPJField(blank=True, max_length=18, null=True)),
            ],
        ),
    ]
