# Generated by Django 3.2.18 on 2023-03-26 20:53

import apps.medicao_lente.models
from django.db import migrations, models
import django_cpf_cnpj.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DadosMedicao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('OS', models.CharField(blank=True, max_length=255, null=True)),
                ('horizontal', models.FloatField(blank=True, null=True)),
                ('vertical', models.FloatField(blank=True, null=True)),
                ('diagonalMaior', models.FloatField(blank=True, null=True)),
                ('DNP', models.IntegerField(blank=True, null=True)),
                ('altura', models.IntegerField(blank=True, null=True)),
                ('leituraDireito', models.BooleanField(blank=True, null=True)),
                ('leituraEsquerdo', models.BooleanField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=apps.medicao_lente.models.generate_uuid4_filename)),
                ('dataCriacao', models.DateTimeField(auto_now_add=True, null=True)),
                ('cnpjOtica', django_cpf_cnpj.fields.CNPJField(blank=True, max_length=18, null=True)),
                ('cnpjLaboratorio', django_cpf_cnpj.fields.CNPJField(blank=True, max_length=18, null=True)),
            ],
            options={
                'db_table': 'dados_medicao',
                'ordering': ['-dataCriacao'],
            },
        ),
    ]
