# Generated by Django 4.2.1 on 2023-06-19 11:32

import apps.medicao_lente.models
from django.db import migrations, models
import django_cpf_cnpj.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DadosMedicao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('OS', models.CharField(blank=True, max_length=255, null=True)),
                ('horizontal', models.FloatField(blank=True, null=True)),
                ('vertical', models.FloatField(blank=True, null=True)),
                ('diagonal_maior', models.FloatField(blank=True, null=True)),
                ('imagem_lente', models.ImageField(blank=True, null=True, upload_to=apps.medicao_lente.models.generate_uuid4_filename)),
                ('oma', models.TextField(blank=True, null=True)),
                ('dnp', models.IntegerField(blank=True, null=True)),
                ('ponte', models.IntegerField(blank=True, null=True)),
                ('altura', models.IntegerField(blank=True, null=True)),
                ('processado', models.BooleanField(default=False)),
                ('data_criacao', models.DateTimeField(auto_now_add=True, null=True)),
                ('cnpj_otica', django_cpf_cnpj.fields.CNPJField(blank=True, max_length=18, null=True)),
                ('cnpj_laboratorio', django_cpf_cnpj.fields.CNPJField(blank=True, max_length=18, null=True)),
            ],
            options={
                'db_table': 'dados_medicao',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
