# Generated by Django 4.2.1 on 2023-05-14 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicao_lente', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dadosmedicao',
            name='processado',
            field=models.BooleanField(default=False),
        ),
    ]
