# Generated by Django 3.2.18 on 2023-03-27 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicao_lente', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dadosmedicao',
            name='ponte',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
