# Generated by Django 4.1.7 on 2023-03-25 04:50

import apps.medicao_lente.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicao_lente', '0002_alter_dadosmedicao_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadosmedicao',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.medicao_lente.models.generate_uuid4_filename),
        ),
    ]
