# Generated by Django 4.2.1 on 2023-06-20 15:15

from django.db import migrations, models

import apps.medicao_lente.models


class Migration(migrations.Migration):
    dependencies = [
        ('medicao_lente', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dadosmedicao',
            name='oma_file',
            field=models.FileField(blank=True, null=True,
                                   upload_to=apps.medicao_lente.models.generate_uuid4_filename_txt),
        ),
    ]
