# Generated by Django 3.2.18 on 2023-03-26 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicao_lente', '0002_alter_dadosmedicao_datacriacao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dadosmedicao',
            options={'ordering': ['-dataCriacao'], 'verbose_name': 'Dado Medicao', 'verbose_name_plural': 'Dados Medições'},
        ),
        migrations.AlterModelTable(
            name='dadosmedicao',
            table='dados_medicao',
        ),
    ]
