# Generated by Django 4.2.1 on 2023-06-20 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicao_lente', '0003_dadosmedicao_oma_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dadosmedicao',
            old_name='diagonal_maior',
            new_name='diagonal',
        ),
    ]
