# Generated by Django 4.2.1 on 2023-07-04 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicao_lente', '0004_rename_diagonal_maior_dadosmedicao_diagonal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadosmedicao',
            name='OS',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
