# Generated by Django 4.2.1 on 2023-07-24 02:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('medicao_lente', '0005_alter_dadosmedicao_os'),
    ]

    operations = [
        migrations.AddField(
            model_name='dadosmedicao',
            name='lado',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dadosmedicao',
            name='oma_file',
            field=models.FileField(blank=True, null=True, upload_to='oma-lens/'),
        ),
    ]
