# Generated by Django 3.2.18 on 2023-05-02 12:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuarios',
            options={'ordering': ['-data_criacao'], 'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.RenameField(
            model_name='usuarios',
            old_name='cellPhone',
            new_name='cellphone',
        ),
        migrations.RenameField(
            model_name='usuarios',
            old_name='dataCriacao',
            new_name='data_criacao',
        ),
        migrations.RenameField(
            model_name='usuarios',
            old_name='fullName',
            new_name='fullname',
        ),
        migrations.RenameField(
            model_name='usuarios',
            old_name='resetPassword',
            new_name='reset_password',
        ),
    ]
